"""
automation/security_tools.py

Security-testing helper: report templates, scan-result organisation,
result summarisation, project folder scaffolding, and documentation
references.  Designed for authorised security work only.
"""

from __future__ import annotations

import logging
import os
import re
import shutil
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Project folder structure
# ---------------------------------------------------------------------------

_PENTEST_TEMPLATE: dict[str, str | list[str]] = {
    "01-Reconnaissance": [
        "nmap",
        "subdomains",
        "screenshots",
    ],
    "02-Exploitation": [],
    "03-Post-Exploitation": [
        "privesc",
        "loot",
    ],
    "04-Lateral-Movement": [],
    "05-Reporting": [
        "findings",
        "evidence",
    ],
    "Tools": [],
    "Scans": [],
}

_TOOL_DOCS: dict[str, str] = {
    "nmap": "https://nmap.org/docs.html",
    "wireshark": "https://www.wireshark.org/docs/",
    "burp suite": "https://portswigger.net/burp/documentation",
    "metasploit": "https://docs.metasploit.com/",
    "nessus": "https://docs.tenable.com/nessus/",
    "nikto": "https://github.com/sullo/nikto/wiki",
    "gobuster": "https://github.com/OJ/gobuster#readme",
    "sqlmap": "https://github.com/sqlmapproject/sqlmap/wiki",
    "hydra": "https://github.com/vanhauser-thc/thc-hydra",
    "john": "https://www.openwall.com/john/doc/",
    "aircrack": "https://www.aircrack-ng.org/documentation.html",
    "aircrack-ng": "https://www.aircrack-ng.org/documentation.html",
    "ffuf": "https://github.com/ffuf/ffuf#usage",
    "zap": "https://www.zaproxy.org/docs/",
    "netcat": "https://nc110.sourceforge.io/",
}

# ---------------------------------------------------------------------------
# Project management
# ---------------------------------------------------------------------------


def create_project_structure(project_name: str, base_dir: str | None = None) -> dict:
    """Create a pentest project folder structure under *base_dir*.

    Structure:
        <base_dir>/<project_name>/
            01-Reconnaissance/nmap/
            01-Reconnaissance/subdomains/
            01-Reconnaissance/screenshots/
            02-Exploitation/
            03-Post-Exploitation/privesc/
            03-Post-Exploitation/loot/
            04-Lateral-Movement/
            05-Reporting/findings/
            05-Reporting/evidence/
            Tools/
            Scans/
    """
    if base_dir is None:
        base_dir = str(Path.home() / "Desktop")
    root = Path(base_dir).expanduser().resolve() / project_name
    try:
        root.mkdir(parents=True, exist_ok=True)
        created: list[str] = []
        for folder, subs in _PENTEST_TEMPLATE.items():
            fpath = root / folder
            fpath.mkdir(exist_ok=True)
            created.append(str(fpath))
            if isinstance(subs, list):
                for sub in subs:
                    (fpath / sub).mkdir(parents=True, exist_ok=True)
                    created.append(str(fpath / sub))
        logger.info("Created project structure at %s", root)
        return {
            "success": True,
            "message": f"Created pentest project '{project_name}' at {root}.",
            "details": {"root": str(root), "folders": created},
        }
    except Exception as exc:
        logger.error("Failed to create project structure: %s", exc)
        return {"success": False, "message": f"Could not create project: {exc}"}


# ---------------------------------------------------------------------------
# Report generation
# ---------------------------------------------------------------------------

_REPORT_TEMPLATE = """# Penetration Test Report

**Client:** {client_name}
**Project:** {project_name}
**Date:** {date}
**Tester:** [Name]

---

## Executive Summary

[Brief summary of findings]

## Scope

[In-scope targets and exclusions]

## Methodology

[Testing approach and tools used]

## Findings

### Critical
1. **Title** — *Description, impact, remediation*

### High
1. **Title** — *Description, impact, remediation*

### Medium
1. **Title** — *Description, impact, remediation*

### Low
1. **Title** — *Description, impact, remediation*

## Appendix

### A — Scan Results
*Attach Nmap, Burp, and other scan outputs.*

### B — Evidence
*Screenshots, logs, and proof of concept.*

---

*Report generated by JARVIS on {date}*
"""


def create_pentest_report(client_name: str, project_name: str, output_dir: str | None = None) -> dict:
    """Generate a templated pentest report markdown file."""
    if output_dir is None:
        output_dir = str(Path.home() / "Desktop")
    dst = Path(output_dir).expanduser().resolve() / f"{project_name}_Pentest_Report.md"
    try:
        dst.parent.mkdir(parents=True, exist_ok=True)
        content = _REPORT_TEMPLATE.format(
            client_name=client_name or "[Client Name]",
            project_name=project_name or "[Project]",
            date=datetime.now().strftime("%Y-%m-%d"),
        )
        dst.write_text(content, encoding="utf-8")
        logger.info("Created pentest report at %s", dst)
        return {
            "success": True,
            "message": f"Created pentest report at {dst}.",
            "details": {"path": str(dst)},
        }
    except Exception as exc:
        return {"success": False, "message": f"Could not create report: {exc}"}


# ---------------------------------------------------------------------------
# Scan result organisation
# ---------------------------------------------------------------------------


def organize_scan_results(source_dir: str, project_name: str, base_dir: str | None = None) -> dict:
    """Organise scan output files into the Scans folder of a project.

    Files are grouped by date (today's results get a 'YYYY-MM-DD' subfolder)
    and by tool name inferred from the filename or extension.
    """
    src = Path(source_dir).expanduser().resolve()
    if not src.is_dir():
        return {"success": False, "message": f"Source directory not found: {source_dir}"}

    if base_dir is None:
        base_dir = str(Path.home() / "Desktop")
    scans_dir = Path(base_dir).expanduser().resolve() / project_name / "Scans"
    try:
        scans_dir.mkdir(parents=True, exist_ok=True)
    except Exception as exc:
        return {"success": False, "message": f"Could not create scans directory: {exc}"}

    today = datetime.now().strftime("%Y-%m-%d")
    dest = scans_dir / today
    dest.mkdir(exist_ok=True)

    moved = 0
    scan_extensions = {".xml", ".nmap", ".gnmap", ".txt", ".csv", ".html", ".json", ".cap", ".pcap", ".pcapng"}
    for entry in src.iterdir():
        if entry.is_file() and entry.suffix.casefold() in scan_extensions:
            try:
                shutil.move(str(entry), str(dest / entry.name))
                moved += 1
            except Exception as exc:
                logger.warning("Could not move %s: %s", entry.name, exc)

    if moved:
        msg = f"Moved {moved} scan result(s) to {dest}."
        logger.info(msg)
        return {"success": True, "message": msg, "details": {"count": moved, "destination": str(dest)}}
    return {"success": True, "message": "No scan result files found to organise."}


# ---------------------------------------------------------------------------
# Result summarisation
# ---------------------------------------------------------------------------


def summarize_scan_results(file_path: str) -> dict:
    """Parse and summarise a scan result file.

    Supports:
      - Nmap XML (.nmap, .xml)
      - Nmap greppable (.gnmap)
      - Nmap normal output (.nmap)
      - Simple text logs with IP:port patterns
    """
    path = Path(file_path).expanduser().resolve()
    if not path.exists():
        return {"success": False, "message": f"File not found: {file_path}"}

    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except Exception as exc:
        return {"success": False, "message": f"Could not read file: {exc}"}

    suffix = path.suffix.casefold()
    summary: dict[str, Any] = {"file": path.name, "type": "unknown"}
    lines = text.splitlines()

    # Nmap XML
    if suffix in (".xml",) and "nmaprun" in text:
        import xml.etree.ElementTree as ET
        try:
            root = ET.fromstring(text)
            hosts = []
            for host in root.findall(".//host"):
                addr_el = host.find("address")
                ip = addr_el.get("addr", "") if addr_el is not None else ""
                ports = []
                for port in host.findall(".//port"):
                    port_id = port.get("portid", "")
                    state_el = port.find("state")
                    state = state_el.get("state", "") if state_el is not None else ""
                    svc_el = port.find("service")
                    svc = svc_el.get("name", "") if svc_el is not None else ""
                    if state == "open":
                        ports.append(f"{port_id}/{svc}")
                hosts.append({"ip": ip, "open_ports": ports})
            open_count = sum(len(h["open_ports"]) for h in hosts)
            summary = {
                "type": "nmap_xml",
                "hosts_scanned": len(hosts),
                "total_open_ports": open_count,
                "hosts": hosts,
                "message": f"Nmap scan: {len(hosts)} host(s), {open_count} open port(s).",
            }
        except Exception:
            summary = {"type": "nmap_xml", "error": "Could not parse XML"}

    # Nmap greppable
    elif suffix == ".gnmap":
        hosts = []
        for line in lines:
            if line.startswith("Host:"):
                parts = line.split(" ")
                ip = parts[0].replace("Host:", "").strip() if len(parts) > 0 else ""
                open_ports = re.findall(r"(\d+)/open/", line)
                hosts.append({"ip": ip, "open_ports": open_ports})
        summary = {
            "type": "nmap_gnmap",
            "hosts_scanned": len(hosts),
            "total_open_ports": sum(len(h["open_ports"]) for h in hosts),
            "hosts": hosts,
            "message": f"Nmap scan: {len(hosts)} host(s).",
        }

    # Nmap normal / text output
    elif suffix == ".nmap" or "nmap" in text[:200].lower():
        hosts = []
        current_ip = ""
        open_ports: list[str] = []
        for line in lines:
            m = re.match(r"^Nmap scan report for\s+(.+?)\s*\(([\d.]+)\)\s*$", line)
            if m:
                if current_ip and open_ports:
                    hosts.append({"ip": current_ip, "open_ports": list(open_ports)})
                current_ip = m.group(2)
                open_ports = []
            m2 = re.match(r"^(\d+)/tcp\s+open\s+(\S+)", line)
            if m2:
                open_ports.append(f"{m2.group(1)}/{m2.group(2)}")
        if current_ip and open_ports:
            hosts.append({"ip": current_ip, "open_ports": list(open_ports)})
        summary = {
            "type": "nmap_normal",
            "hosts_scanned": len(hosts),
            "total_open_ports": sum(len(h["open_ports"]) for h in hosts),
            "hosts": hosts,
            "message": f"Nmap scan: {len(hosts)} host(s).",
        }

    # Generic: extract IP:port patterns
    else:
        ip_port_pattern = re.findall(r"(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})[:\s]+(\d+)", text)
        unique_ports = sorted(set(p[1] for p in ip_port_pattern), key=int) if ip_port_pattern else []
        unique_ips = sorted(set(p[0] for p in ip_port_pattern))
        summary = {
            "type": "generic",
            "unique_ips": unique_ips,
            "unique_ports": unique_ports,
            "line_count": len(lines),
            "message": f"Found {len(unique_ips)} IP(s) and {len(unique_ports)} port(s).",
        }

    return {"success": True, "message": summary["message"], "details": summary}


# ---------------------------------------------------------------------------
# Documentation
# ---------------------------------------------------------------------------


def open_tool_documentation(tool_name: str) -> dict:
    """Open the documentation URL for a security tool in the default browser."""
    key = tool_name.strip().casefold()
    url = _TOOL_DOCS.get(key)
    if not url:
        names = ", ".join(sorted(_TOOL_DOCS))
        return {
            "success": False,
            "message": f"No documentation URL for {tool_name!r}. Known tools: {names}",
        }
    try:
        import webbrowser
        webbrowser.open(url)
        return {"success": True, "message": f"Opened {tool_name} documentation.", "details": {"url": url}}
    except Exception as exc:
        return {"success": False, "message": f"Could not open documentation: {exc}"}
